sudo: required
services:
  - docker

before_install:
  - docker build -t drakemage47/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true drakemage47/react-test npm test

after_success:
  - docker build -t drakemage47/multi-client ./client
  - docker build -t drakemage47/multi-nginx ./nginx
  - docker build -t drakemage47/multi-server ./server
  - docker build -t drakemage47/multi-worker ./worker